#!/usr/bin/env python

import os
import datetime


def generate_dates():
    start_year = int(os.environ['START_YEAR'])
    start_month = int(os.environ['START_MONTH'])
    start_day = int(os.environ['START_DAY'])
    cutoff_days = int(os.environ['CUTOFF_DAYS'])  # exclude the last X days

    epoch = datetime.datetime(start_year, start_month, start_day)
    cutoff = datetime.datetime.now() - datetime.timedelta(cutoff_days, 0, 0)

    i = epoch
    while i < cutoff:
        yield i
        i += datetime.timedelta(1, 0, 0)


def main():
    for day in generate_dates():
        print day.strftime('%Y-%m-%d')


if __name__ == '__main__':
    main()
